# Generated by Django 4.1 on 2023-02-18 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="News",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("author", models.CharField(max_length=255, null=True)),
                ("title", models.TextField()),
                ("description", models.TextField()),
                ("url", models.URLField()),
            ],
        ),
    ]
