# Generated by Django 4.1 on 2023-02-18 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="news", name="url_to_image", field=models.URLField(null=True),
        ),
    ]
