# Generated by Django 4.1 on 2023-02-18 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0002_alter_news_url_to_image"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="news",
            options={"ordering": ["-published_at"], "verbose_name_plural": "News"},
        ),
        migrations.AlterField(
            model_name="news", name="title", field=models.CharField(max_length=511),
        ),
        migrations.AlterUniqueTogether(
            name="news", unique_together={("title", "source_name")},
        ),
    ]
